work_on_booking_seats_work_in_progress
studentrohit123/ROR_Demo_project pull request #12
Opened 2024-09-02 13:49 UTC by studentrohit123

2024-09-03 04:56 UTC, Kapil0187 requested changes

2024-09-03 04:56 UTC, Kapil0187 commented on app/models/booking.rb
> +    byebug
don't push byebug , debugger in github

2024-09-03 04:56 UTC, Kapil0187 commented on app/controllers/bookings_controller.rb
> +    byebug
remove byebug from here

2024-09-03 04:56 UTC, Kapil0187 commented on app/views/bookings/new.html.erb
> +<% byebug %>
remove byebug from here

2024-09-03 05:12 UTC, studentrohit123 commented on app/models/booking.rb
> +    byebug
ok

2024-09-03 07:51 UTC, vinayaklovanshi requested changes

2024-09-03 07:51 UTC, vinayaklovanshi commented on app/controllers/bookings_controller.rb
> +  def set_bus
Method name is incorrect, why we are taking it as set_bus when we are finding tain?

2024-09-03 07:51 UTC, vinayaklovanshi commented on app/views/bookings/new.html.erb
> +<% byebug %>
Why you are pushing byebug everywhere?

2024-09-04 05:32 UTC, vinayaklovanshi requested changes

2024-09-04 05:32 UTC, vinayaklovanshi commented on app/controllers/bookings_controller.rb
Remove this extra space

2024-09-04 05:32 UTC, vinayaklovanshi commented on app/controllers/bookings_controller.rb
> +  def set_bookable
Use this:

@bookable = params[:bookable_type].constantize.find(params[:bookable_id])

2024-09-04 05:56 UTC, merged